services:
  the_blog:
    container_name: the_blog
    build: .
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - sqlite:/app/db.sqlite3
    command:
      [
        "sh",
        "-c",
        "npx tsx src/db/drizzle/migrate.ts && npx tsx src/db/drizzle/seed.ts && node server.js",
      ]
volumes:
  sqlite:
    driver: local
