services:
  the_blog:
    container_name: the_blog
    build: .
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/db.sqlite3
    command: ["sh", "-c", "npm run migrate && npm start"]
