services:
  the_blog:
    container_name: the_blog
    build: .
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/db.sqlite3
    restart: unless-stopped
    command:
      [
        "sh",
        "-c",
        "mkdir -p /app/data && npm run migrate && npm run seed && node server.js",
      ]
